version: '3.1'

volumes: 
  db: null

services: 
  db:
    image: mariadb:10.3.16
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: 4pet
      MYSQL_USER: 4pet
      MYSQL_PASSWORD: 4pet
    ports: 
      - 3306:3306
    volumes: 
        - ./scripts:/docker-entrypoint-initdb.d
        - db:/var/lib/mysql
